apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::459905759037:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-DVOVFOZ6WXSK
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::459905759037:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-19T14:53:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1500"
  uid: edafbf9a-bed2-4296-8fd6-a30ae37d5636
