apiVersion: v1
data:
  mapRoles: |
    - groups:
    - system:masters
    rolearn: arn:aws:iam::459905759037:role/UdacityFlaskDeployCBKubectlRole
    username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-19T12:50:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2210"
  uid: 5680e04a-afa5-440f-89d7-a55c0b50ea6d
